name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue had no activity recently 😕 Stale issues will be closed automatically after sometime.'
        stale-pr-message: 'This pull request had no activity recently and probably needs attention 🤓'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
